#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Символы вендорских функций для линковщика: ld/symbols.ld и ld/symbols-ucode.ld.

Источник истины — src/asm/{fw,uc}/blocks.json, то есть РОВНО те имена, что
сейчас в дереве. Раньше скрипт читал ref/SYMS.txt и ref/FN-NAMES.txt; эти
файлы сняты один раз на 81 % покрытия и больше не обновлялись, из-за чего
после волны переименований 2852 блока из 3332 остались без символа, а 611
символов указывали на имена, которых больше нет. Ревизия 2026-09-24.

SYMS.txt остаётся необязательным ДОПОЛНЕНИЕМ: оттуда берутся размеры для
комментария и адреса, которых нет в blocks.json (таких быть не должно).

Выход раздельный: uc_code исполняется ДРУГИМ процессором, звать оттуда/туда
обычным bl нельзя, и смешивать их в одном скрипте — верный способ собрать
нерабочий образ.

Схема имён:
  * каждому блоку даётся адресный алиас  sub_008c2190  — адресуемо всё;
  * плюс человекочитаемый символ (:: -> __, прочее -> _);
  * всё через PROVIDE: если наш код определит такой символ сам, победит наш.
"""
import argparse, json, os, re, sys
from collections import defaultdict

UC_BASE = 0x920000
MACHINE = ('sub_', 'blk_', 'FUN_', 'thunk_')


def mangle(n):
    n = n.replace('::', '__')
    n = re.sub(r'[^A-Za-z0-9_]', '_', n)
    if n and n[0].isdigit():
        n = '_' + n
    return n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--blocks-fw', default='src/asm/fw/blocks.json')
    ap.add_argument('--blocks-uc', default='src/asm/uc/blocks.json')
    ap.add_argument('--syms', default='ref/SYMS.txt', help='необязательное дополнение')
    ap.add_argument('--out', default='ld/symbols.ld')
    ap.add_argument('--out-ucode', default='ld/symbols-ucode.ld')
    a = ap.parse_args()

    groups = {'fw': {}, 'uc': {}}
    for key, path in (('fw', a.blocks_fw), ('uc', a.blocks_uc)):
        for b in json.load(open(path))['blocks']:
            groups[key][b['addr']] = (b['size'], b['name'])

    # адреса, которых нет в дереве, — только из SYMS.txt (штатно таких нет)
    добавлено = 0
    if os.path.exists(a.syms):
        for l in open(a.syms):
            if not l.startswith('SYM'):
                continue
            p = l.split(None, 4)
            ad, sz, kind, nm = int(p[1], 16), int(p[2]), p[3], p[4].strip()
            key = 'uc' if ad >= UC_BASE else 'fw'
            if ad not in groups[key]:
                groups[key][ad] = (sz, nm if kind == 'name' else 'sub_%06x' % ad)
                добавлено += 1

    stats = {}
    for key, path in (('fw', a.out), ('uc', a.out_ucode)):
        used, lines, named = defaultdict(int), [], 0
        for addr in sorted(groups[key]):
            size, name = groups[key][addr]
            alias = 'sub_%08x' % addr
            lines.append('PROVIDE(%-40s = 0x%08x);  /* %5d B */' % (alias, addr, size))
            if not name.startswith(MACHINE):
                m = mangle(name)
                used[m] += 1
                if used[m] > 1:
                    m = '%s_%08x' % (m, addr)      # разводим тёзок адресом
                if m != alias:
                    lines.append('PROVIDE(%-40s = 0x%08x);' % (m, addr))
                    named += 1
        # В ТЕКСТЕ ШАПКИ НЕ ДОЛЖНО БЫТЬ `*/`. Комментарий linker script
        # закрывается первой же такой парой, и всё, что идёт дальше, ld
        # разбирает как код: путь вида src/asm/*/blocks.json в шапке даёт
        # "syntax error" на второй строке. Кириллица, вопреки первому
        # подозрению, ld не мешает — проверено отдельно.
        hdr = [
            '/* GENERATED by tools/gen_symbols_ld.py from the per-segment blocks.json files.',
            ' * Do not edit: run "make symbols" after any renaming.',
            ' * %s: %d blocks, %d with readable names.' % (
                'fw_code' if key == 'fw' else 'uc_code (SEPARATE processor!)',
                len(groups[key]), named),
            ' * Keep this header free of the comment terminator sequence.',
            ' */', '']
        os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
        open(path, 'w').write('\n'.join(hdr + lines) + '\n')
        stats[key] = (len(groups[key]), named, path)

    for key in ('fw', 'uc'):
        n, named, path = stats[key]
        print('%-8s блоков %4d, читаемых имён %4d -> %s' %
              ('fw_code' if key == 'fw' else 'uc_code', n, named, path))
    if добавлено:
        print('дополнено из %s: %d адресов вне дерева' % (a.syms, добавлено))
    return 0


if __name__ == '__main__':
    sys.exit(main())
